# Generated by Django 5.0.4 on 2024-05-14 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='isim')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('konu', models.CharField(max_length=100, verbose_name='konu')),
                ('mesaj', models.TextField(max_length=255, verbose_name='mesaj')),
            ],
        ),
        migrations.CreateModel(
            name='Gamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('age', models.IntegerField()),
                ('profile_image', models.ImageField(upload_to='images/gamers_image/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamer',
                'verbose_name_plural': 'Gamers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('category', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/game_image/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('players_who_played', models.ManyToManyField(blank=True, related_name='games_played', to='account.gamers')),
            ],
            options={
                'verbose_name': 'Oyun',
                'verbose_name_plural': 'Oyunlar',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='gamers',
            name='best_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_players', to='account.games'),
        ),
    ]
