# Generated by Django 5.0.4 on 2024-05-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamers',
            name='name',
        ),
    ]
