# Generated by Django 5.0.4 on 2024-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_gamers_age_alter_gamers_best_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='players_who_played',
        ),
        migrations.AddField(
            model_name='gamers',
            name='games_played',
            field=models.ManyToManyField(blank=True, to='account.games'),
        ),
    ]
