# Generated by Django 5.0.4 on 2024-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_games_players_who_played_gamers_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
